### ISSUE TITLE
Please consider adding support Protocol 3.4

### ISSUE THREAD

**Issue by xia0linz1** [leeyuentuen/localtuya#35]
Rospogrigio/localtuya has released their version 5.0.0 which added support Protocol 3.4. Please consider merging the branch to support
the tuya latest HW firmware.

**Comment by leeyuentuen** [comment]
i've release a beta version with this protocol

there is some changes for me on the response of the data:

A temperature sensor was:
```
 - parent_gateway: bf5c95cfe466ad6cdxxxx
     device_id: a4c138e91c10a5e6
     friendly_name: "Local tmp Sensor"
     entities:
      - platform: sensor
        friendly_name: Local tmp Humidity
        id: 101
        device_class: humidity
        scaling: 0.01
        unit_of_measurement: "%"
      - platform: sensor
        friendly_name: Local tmp Battery
        id: 102
        device_class: battery
        unit_of_measurement: "%"
      - platform: sensor
        friendly_name: Local tmp Temperature
        id: 103
        scaling: 0.01
        device_class: temperature
        unit_of_measurement: "°C"
```
but on this protocol 3.4, it has been changed to:
```
   - parent_gateway: bf5c95cfe466ad6cdxxxx
     device_id: a4c138e91c10a5e6
     friendly_name: "Local tmp Sensor"
     entities:
      - platform: sensor
        friendly_name: Local tmp Humidity
        id: 2
        device_class: humidity
        scaling: 0.1
        unit_of_measurement: "%"
      - platform: sensor
        friendly_name: Local tmp Battery
        id: 4
        device_class: battery
        unit_of_measurement: "%"
      - platform: sensor
        friendly_name: Local tmp Temperature
        id: 1
        scaling: 0.1
        device_class: temperature
        unit_of_measurement: "°C"
```

The yaml to add gateway with protocol 3.4 is this:
```
   - host: 172.16.0.xx
     device_id: bf5c95cfe466ad6cdxxxx
     local_key: fdb94bffb6844dee
     friendly_name: "gateway 2"
     protocol_version: "3.4"
     is_gateway: true
```
