### ISSUE TITLE
Any DP examples for a bluetooth bulb?

### ISSUE THREAD

**Issue by felipecrs** [leeyuentuen/localtuya#37]
I'm trying to configure mine without much success.

**Comment by leeyuentuen** [comment]
if you go to tuya iot:
https://eu.iot.tuya.com/cloud/explorer

search for "Get Device Specification Attribute"
and search then for that device_id, you will see right the dp codes

<img width="245" alt="image" src="https://user-images.githubusercontent.com/1487966/216643854-b508dee1-744a-44e6-be05-9f61da19a8aa.png">

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/1487966/216643711-07e08aa3-2b3b-46b0-be3d-c8763528300e.png">

**Comment by felipecrs** [comment]
Wow this is amazing! I'll try that.

**Comment by felipecrs** [comment]
Well, this is the output. I'm not sure how should I use it. =/

```
{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "do_not_disturb",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "do_not_disturb",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1675463071103,
  "tid": "875ccacca41111ed858bc232723a3483"
}
```

**Comment by leeyuentuen** [comment]
it seems the dj didn't give dp code
same here

```
{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "ON/OFF",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "lang_config": {
          "colour": "Colour",
          "music": "Music",
          "scene": "Scene",
          "white": "White"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "colour_data_v2",
        "lang_config": {
          "unit": ""
        },
        "name": "Colour ",
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}"
      },
      {
        "code": "scene_data_v2",
        "lang_config": {
          "unit": ""
        },
        "name": "Scene",
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Timer",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "lang_config": {
          "unit": ""
        },
        "name": "Adjust",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "ON/OFF",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "lang_config": {
          "colour": "Colour",
          "music": "Music",
          "scene": "Scene",
          "white": "White"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "colour_data_v2",
        "lang_config": {
          "unit": ""
        },
        "name": "Colour ",
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}"
      },
      {
        "code": "scene_data_v2",
        "lang_config": {
          "unit": ""
        },
        "name": "Scene",
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Timer",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "lang_config": {
          "unit": ""
        },
        "name": "Adjust",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      }
    ]
  },
  "success": true,
  "t": 1675464393963,
  "tid": "9bd5f29ca41411edbd98a6d801a7eabc"
```

**Comment by felipecrs** [comment]
Ok, here's what tuya wizard gives me:

```json
[
  {
    name: 'Hub Bluetooth e ZigBee',
    id: 'eb41b8f336925ed5eczxwg',
    key: '<my key>',
    subDevices: [
      {
        name: 'Luz do corredorzinho',
        id: 'eb2ce7tlym7ifhpp',
        cid: 'dc234dc5aea1'
      }
    ]
  }
]
```

Here's how I configured the integration:

```yaml
localtuya:
  - host: "192.168.1.27"
    device_id: eb41b8f336925ed5eczxwg
    local_key: <my key>
    friendly_name: Tuya Hub
    protocol_version: "3.3"
    is_gateway: true
  - parent_gateway: eb41b8f336925ed5eczxwg
    device_id: dc234dc5aea1
    friendly_name: Bluetooth Light
    entities:
      - platform: light
        friendly_name: My Light
        id: 20
        color_mode: 21 # Optional, usually 2 or 21, default: "none"
        #brightness: 22 # Optional, usually 3 or 22, default: "none"
        #color_temp: 23 # Optional, usually 4 or 23, default: "none"
        color_temp_reverse: false # Optional, default: false
        color: 24 # Optional, usually 5 (RGB_HSV) or 24 (HSV), default: "none"
        brightness_lower: 10 # Optional, usually 0 or 29, default: 29
        brightness_upper: 1000 # Optional, usually 255 or 1000, default: 1000
        color_temp_min_kelvin: 2700 # Optional, default: 2700
        color_temp_max_kelvin: 6500 # Optional, default: 6500
        scene: 25 # Optional, usually 6 (RGB_HSV) or 25 (HSV), default: "none"
        music_mode: False # Optional, some use internal mic, others, phone mic. Only internal mic is supported, default: "False"
```

But in my HA logs I only get this:

```
2023-02-03 20:40:44.441 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 369, in _make_connection
    await self._get_sub_device_status(subitem)
  File "/config/custom_components/localtuya/common.py", line 439, in _get_sub_device_status
    status = await self._interface.status(cid)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 596, in status
    raise Exception("Unexpected sub-device cid", cid)
Exception: ('Unexpected sub-device cid', ('dc234dc5aea1', {'dps': {20: None, 21: None, 24: None, 25: None}, 'retry_status': True}))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 380, in _make_connection
    await self._interface.close()
KeyError: (-100, )
2023-02-03 20:40:44.469 WARNING (MainThread) [custom_components.localtuya.common] [eb4...xwg] Connect to gateway 192.168.1.27 failed
```

Tons of it.
