### ISSUE TITLE
Add button support

### ISSUE THREAD

**Issue by atlantden** [leeyuentuen/localtuya#47]
We need support for Zigbee buttons in integration, such as 1-3 key switches and similar ones. Currently, it is not possible to add them correctly through a single entity, as, for example, the sensor does not change state with a sequential single press - the status remains the same. The status only changes when a different action is taken, such as making a double press after a single press, and so on.

**Comment by alexualbu** [comment]
I am actually looking to buy a zigbee remote / switch. Do you have them set-up as different entities right now? Can you post the DPs details, maybe from tuyaconsole?

**Comment by atlantden** [comment]
I have the remote controls, but they are almost useless with LocalTuya because when I press the button again, no event occurs and the state does not change. The event and state changes only occur when using different button presses. For example, a second single click won't trigger an event in HA, only a double click after a single click will. This is the essence of the problem. I can provide a section of my configuration for the three-button remote control if needed.

```
#remote in the hall
  - parent_gateway: my_gateway_id # This tells it is a sub-device dependent on a parent gateway
    device_id: remote_cid (mac-address) # The cid of sub-device
    friendly_name: remote in the hall
    entities:
      - platform: sensor
        friendly_name: Button 1
        id: 1
      - platform: sensor
        friendly_name: Button 2
        id: 2
      - platform: sensor
        friendly_name: Button 3
        id: 3
      - platform: sensor
        friendly_name: Battery
        id: 10
        device_class: battery
```
