### ISSUE TITLE
Support for time-based positioned cover controllers

### ISSUE THREAD

**Issue by darth-aragoth** [leeyuentuen/localtuya#59]
Please add support for time-based positioning in cover controllers.

My cover controllers have only one DP with value 1, 2 or 3 (move up, move down, stop, I don't know in what order). In config I have time-based positioning mode and "1_2_3" command set - that works fine with rospogrigio's localtuya version. At the beginning, I had to measure time needed to full-close each cover.

In config.yaml:
```
  - host: x.x.x.x
    device_id: xxx
    local_key: xxx
    friendly_name: Roleta 1
    protocol_version: "3.3"
    entities:
      - platform: cover
        friendly_name: Roleta 1
        id: 1
        commands_set: "1_2_3"
        positioning_mode: "timed"
        span_time: 20.8
```

In SmartLife config:
```
	"activeTime": 1623492697,
	"devId": "xxx",
	"displayOrder": 0,
	"dpMaxTime": 1679332060540,
	"dps": {
		"1": "3"
	},
	"errorCode": 0,
	"iconUrl": "https://images.tuyaeu.com/smart/icon/15524566468s3d5rsnldv_0.png",
	"isShare": false,
	"key": "xxx",
	"lat": "xxx",
	"localKey": "xxx",
	"lon": "xxx",
	"moduleMap": {
		"mcu": {
			"cadv": "",
			"isOnline": true,
			"verSw": "1.0.2"
		},
		"wifi": {
			"bv": "5.56",
			"cadv": "",
			"isOnline": true,
			"pv": "2.2",
			"verSw": "1.0.2"
		}
	},
	"name": "Rolety parter - sypialnia",
	"productId": "xxx",
	"resptime": 0,
	"runtimeEnv": "prod",
	"timezoneId": "Europe/Warsaw",
	"uuid": "xxx",
	"virtual": false

```

My cover controllers are similar to the one in the picture:

![image](https://user-images.githubusercontent.com/72323164/232768812-48a0b36e-ad23-41b4-88bc-a804c2daea93.png)

They only control the motor that raises and lowers the cover, but they have no feedback about the position of the cover, so it has to be time-controlled.
