### ISSUE TITLE
Bluetooth water timer:

### ISSUE THREAD

**Issue by mikeinblue** [leeyuentuen/localtuya#64]
"category": "sfkzq",
"model": "SOP10",
"name": "水阀控制器",
imglink: https://images.tuyacn.com/ecommerce/16119137706294d7a3b33.jpg?x-oss-process=image/format,webp

## The problem
When I added this watering timer ,it shows **Unavailable**. I have set the pd correctly.
Maybe caused "Data point detection failed. Type in a number to add a data point, or 0 to finish or cancel." 

When I added A wifi plug, it works pefectly.

## Environment

- Localtuya version: 3.7beta10
- Home Assistant Core version: **Home Assistant 2023.5.2** 
- [x] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? 

## Configuration `configuration.yaml` or `config_flow`

```yaml
localtuya:
  # Zigbee or Bluetooth gateway
  - host: 192.168.22.208
    device_id: xxxxxxxxxxxx
    local_key: xxxxxxxxxx
    friendly_name: Tuya Gateway
    protocol_version: "3.4"
    is_gateway: true # This tells it is to be treated as a gateway and skip adding entities

  # Devices under a gateway
  # Other than differences on the device itself (ie. no host and local_key), the rest is the same
  #   as a WiFi device
  - parent_gateway: xxxxxxxxxxxxxx # This tells it is a sub-device dependent on a parent gateway
    device_id: xxxxxxxxxxx # The cid of sub-device
    friendly_name: water timer
    entities:
      - platform: switch
        friendly_name: water timer Entity 1
        id: 1
```

## DP dump
{
  "result": {
    "category": "sfkzq",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "time_use",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":2592000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "weather_delay",
        "dp_id": 10,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}"
      },
      {
        "code": "countdown",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "smart_weather",
        "dp_id": 13,
        "type": "Enum",
        "values": "{\"range\":[\"sunny\",\"cloudy\",\"rainy\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 7,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "time_use",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":2592000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "weather_delay",
        "dp_id": 10,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}"
      },
      {
        "code": "countdown",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_state",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\",\"idle\"]}"
      },
      {
        "code": "smart_weather",
        "dp_id": 13,
        "type": "Enum",
        "values": "{\"range\":[\"sunny\",\"cloudy\",\"rainy\"]}"
      },
      {
        "code": "use_time_one",
        "dp_id": 15,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1683860130158,
  "tid": "748ba074f07011ed8819c6e890e871c6"
}
## Provide Home Assistant taceback/logs

2023-05-12 08:08:57.522 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] Sending command 9 (device type: v3.4)
2023-05-12 08:08:57.522 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] Sending payload: b'{"gwId":"6c7984edb1087dd187ozsx","devId":"6c7984edb1087dd187ozsx"}'
2023-05-12 08:08:57.522 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] final payload for cmd 9: b'{"gwId":"6c7984edb1087dd187ozsx","devId":"6c7984edb1087dd187ozsx"}'
2023-05-12 08:08:57.522 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] Dispatching sequence number -100
2023-05-12 08:08:57.522 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] payload b"\x00\x00U\xaa\x00\x00\xda\x06\x00\x00\x00\t\x00\x00\x00tS\xca\xfcv>\xc2\x92\x02\x86U\xe5\x8c[\x7f\xdc\xbd\x02\x99\xf6u\x85K\x8c}\xe4\x0f\xb7\xd4\xcc.Ib\x7f]\xe6\x14\xa68\xe7'\xe7\x08w\x1fb\xc0\x11\xc9bu\x7f\xf2\x1b\x9e\x8463\xfdx\xd1\xfb\xa7\xf3\xf9\x07'\xacw;\x010\xb4)\xb7\xb7#\x18\xa5\xed1\xcdb\xda\xd1\xa6\xb3\x8cm\x87G/N\x84\xf2\x99z\x97\x03\x0b\x8c\x08aj\xb0\xed\x02T\x19O}PG\x00\x00\xaaU" - MessagePayload(cmd=9, payload=b'{"gwId":"6c7984edb1087dd187ozsx","devId":"6c7984edb1087dd187ozsx"}')
2023-05-12 08:08:57.522 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] Command 9 waiting for sequence number -100
2023-05-12 08:08:57.558 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] Dispatching message CMD 9 TuyaMessage(seqno=55814, cmd=9, retcode=0, payload=b'', crc=b'\xb5\xa8\xf1\xb8\xaaM-I\xb5t\xf3\xcd\xe8(\xf6\x15\xe3\xbb\x01\xac\x03\xf8\x1d\x10\xb1h\xeb\x90Jy\x93\xb7', crc_good=True)
2023-05-12 08:08:57.558 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] Got heartbeat response
2023-05-12 08:08:57.558 DEBUG (MainThread) [custom_components.localtuya.pytuya] [6c7...zsx] ACK received for command 9: ignoring it
