### ISSUE TITLE
Unable to use set_position on LocalTuya Covers

### ISSUE THREAD

**Issue by mandishshah** [leeyuentuen/localtuya#66]
## The problem

I'd like to use the `set_position` functionality from HA for my covers. I have configured all my covers at the moment using YAML which didn't let me know set the `min_value`, `max_value`, or the `step_size` values during the initial configuration. However, the config flow did allow for this so I am not sure if this is the root issue or not. Are there any workarounds for me to set these and try debugging further.

## Environment
- Localtuya version: 3.6.7
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: 2023.5.3

## Steps to reproduce
Developer Tools -> Services -> Cover: Set Position -> 50% -> Run into an error

## Configuration `configuration.yaml` or `config_flow`
```yaml
- parent_gateway: <> # This tells it is a sub-device dependent on a parent gateway
  device_id: <> # The cid of sub-device
  friendly_name: Dining Room Blind
  entities:
    - platform: cover
      friendly_name: Dining Room Blind
      id: 1
      commands_set: "open_close_stop"
    - platform: number
      friendly_name: Dining Room Blind Percent Control
      id: 2
    - platform: sensor
      friendly_name: Dining Room Blind Current Position
      id: 3
    - platform: sensor
      friendly_name: Dining Room Blind State
      id: 7
```

## Some Logs

```txt
websocket_api script: Error executing script. Error for call_service at pos 1: Entity cover.dining_room_blind does not support this service.
```

```txt
[139624471009056] Error handling message: Entity cover.dining_room_blind does not support this service. (unknown_error)
```
