### ISSUE TITLE
[3.7.0 beta 10] BLE Gateway devices reporting state correctly, but cannot control devices

### ISSUE THREAD

**Issue by zaa94** [leeyuentuen/localtuya#70]
## The problem

I have two [BLE Diivoo water valve timers](https://www.amazon.com/gp/product/B09PYGRM3H/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1) (Tuya category `sfkzq`) each with a WiFi gateway (Tuya category `wg2`) that I've got setup with v3.7.0b10 . I only have the switch and battery level entities configured as that's all I need for my current setup. Both the switch state and battery level state appear to be syncing correctly, but when I attempt to turn on/off the switch to either valve, nothing happens. According to the logs, it looks like once the payload is sent, it hangs, then once it receives an ACK, it stops.

## Environment

- Localtuya version: v3.7.0b10
- Last working localtuya version (if known and relevant): n/a
- Home Assistant Core version: 
  - Home Assistant 2023.6.2
  - Supervisor 2023.06.2
  - Operating System 10.3
- [X] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? 

## Configuration `configuration.yaml` or `config_flow`
```yaml
localtuya:  
  - host: 192.168.XX.XX
    device_id: FRONT_YARD_GW_ID
    local_key: <LOCAL_KEY>
    friendly_name: Front Yard Gateway
    protocol_version: "3.4"
    is_gateway: true
  - parent_gateway: FRONT_YARD_GW_ID
    device_id: FRONT_YARD_CONTROLLER_CID
    friendly_name: Front Yard Sprinkler
    protocol_version: "3.4"
    entities:
      - platform: switch
        friendly_name: Front Yard Sprinkler Valve Switch
        id: 1
      - platform: sensor
        friendly_name: Front Yard Sprinkler Valve Battery
        id: 7
        device_class: battery
        unit_of_measurement: "%"
  - host: 192.168.XX.XX
    device_id: BACK_YARD_GW_ID
    local_key: <LOCAL_KEY>
    friendly_name: Back Yard Gateway
    protocol_version: "3.4"
    is_gateway: true
  - parent_gateway: BACK_YARD_GW_ID
    device_id: BACK_YARD_CONTROLLER_CID
    friendly_name: Back Yard Sprinkler
    protocol_version: "3.4"
    entities:
      - platform: switch
        friendly_name: Back Yard Sprinkler Valve Switch
        id: 1
      - platform: sensor
        friendly_name: Back Yard Sprinkler Valve Battery
        id: 7
        device_class: battery
        unit_of_measurement: "%"
```

## DP dump

**Gateway DPs**
```json
"result": {
    "properties": [
      {
        "code": "up_channel",
        "custom_name": "",
        "dp_id": 1,
        "time": 1686887887646
      },
      {
        "code": "down_channel",
        "custom_name": "",
        "dp_id": 2,
        "time": 1686887887646
      }
    ]
  }
```

**Valve Controller DPs**
```JSON
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1687475984332,
        "value": false
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 4,
        "time": 1686888004302,
        "value": 0
      },
      {
        "code": "battery_percentage",
        "custom_name": "",
        "dp_id": 7,
        "time": 1687475757040,
        "value": 100
      },
      {
        "code": "time_use",
        "custom_name": "",
        "dp_id": 9,
        "time": 1687475984332,
        "value": 190355
      },
      {
        "code": "weather_delay",
        "custom_name": "",
        "dp_id": 10,
        "time": 1687475757080,
        "value": "cancel"
      },
      {
        "code": "countdown",
        "custom_name": "",
        "dp_id": 11,
        "time": 1687475980499,
        "value": 599
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 12,
        "time": 1687475984331,
        "value": "idle"
      },
      {
        "code": "smart_weather",
        "custom_name": "",
        "dp_id": 13,
        "time": 1686888004302,
        "value": "sunny"
      },
      {
        "code": "switch_weather",
        "custom_name": "",
        "dp_id": 14,
        "time": 1687475757104,
        "value": false
      },
      {
        "code": "use_time_one",
        "custom_name": "",
        "dp_id": 15,
        "time": 1687475983000,
        "value": 4
      },
      {
        "code": "cycle_timing",
        "custom_name": "",
        "dp_id": 16,
        "time": 1687475757120,
        "value": "AA=="
      },
      {
        "code": "timer",
        "custom_name": "",
        "dp_id": 17,
        "time": 1687475757128,
        "value": "AA=="
      }
    ]
  }
```

## Provide Home Assistant taceback/logs

```txt
2023-06-22 16:11:42.840 DEBUG (MainThread) [custom_components.localtuya.common] [BACK_YARD_CONTROLLER_CID] Dispatching request request_set_dp to gateway with content {'value': True, 'dp_index': 1}
2023-06-22 16:11:42.841 DEBUG (MainThread) [custom_components.localtuya.common] [BACK_YARD_GW_ID] Received request request_set_dp from BACK_YARD_CONTROLLER_CID with content {'value': True, 'dp_index': 1}
2023-06-22 16:11:42.841 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] Sending command 7 (device type: v3.4)
2023-06-22 16:11:42.842 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] Sending payload: b'{"protocol":5,"t":1687475502,"data":{"dps":{"1":true}},"cid":"BACK_YARD_CONTROLLER_CID"}'
2023-06-22 16:11:42.842 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] final payload for cmd 13: b'3.4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{"protocol":5,"t":1687475502,"data":{"dps":{"1":true}},"cid":"BACK_YARD_CONTROLLER_CID"}'
2023-06-22 16:11:42.844 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] Dispatching sequence number 14629
2023-06-22 16:11:42.844 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] payload b'\x00\x00U\xaa\x00\x009%\x00\x00\x00\r\x00\x00\x00\x84v\xff\x1f\xf7hX&\xaa\xad\x88;\x03\x1e\xf7\x1dD\xd5\xe4\x17q\x16\xd0\xcd\xd7\xf5pr\x01H\xd0a\x95\x9d\xfb"\xeb\x8f\xab\x97s\xd6$I!\x81Z\xcf\xa7\x079\x14\xc0b\xd0/\xc0\xbd\x1a*\xddS\xe8}Wr\xe2|\xf1"\xddm\x0ezaK6\x94J\x87\xac\x86\x85\x9e\x98\x18\xb3-\'\x80\x8e<\xc7\xa3\xf9\xac!5\xed1\xfc\x80&\xe6>M\x16n\x99\xf51\xcc;\xfc\xb3Bys\xa8\xdc\xcc\x8c\xbb\x08\xa2J\xb4\x9f\xcf\x00\x00\xaaU' - MessagePayload(cmd=13, payload=b'{"protocol":5,"t":1687475502,"data":{"dps":{"1":true}},"cid":"BACK_YARD_CONTROLLER_CID"}')
2023-06-22 16:11:42.844 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] Command 13 waiting for sequence number 14629
2023-06-22 16:11:42.855 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] Dispatching message CMD 13 TuyaMessage(seqno=14629, cmd=13, retcode=0, payload=b'', crc=b'\x074\x07\xb34\x18i%\xac\xb8\xd0\xc3\x18j\xf5\xffy\xed\x9d\xdd\xf5\xed;\xben"\xe9\t\xe7\xf4\xbd"', crc_good=True)
2023-06-22 16:11:42.855 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] Dispatching sequence number 14629
2023-06-22 16:11:42.856 DEBUG (MainThread) [custom_components.localtuya.pytuya] [BACK_YARD_GW_ID] ACK received for command 13: ignoring it
```
## Additional information
**Gateway Information**
```json
    "result": {
        "active_time": 1686068403,
        "biz_type": 0,
        "category": "wg2",
        "create_time": 1686068403,
        "icon": "smart/icon/ay1547018215107OLzeG/b6b7db60ecbb436bb77e8a6c00ec4fc5.jpg",
        "id": "XXXXX",
        "ip": "XXXXX",
        "lat": "XXXXX",
        "local_key": "XXXXX",
        "lon": "XXXXX",
        "model": "WG02",
        "name": "XXXXX",
        "online": true,
        "owner_id": "XXXXX",
        "product_id": "v7owd9tzcaninc36",
        "product_name": "Gateway",
        "status": [],
        "sub": true,
        "time_zone": "XXXXX",
        "uid": "XXX",
        "update_time": 1687459834,
        "uuid": "XXX"
    }
```

**Valve Controller Information**
```json

    "result": {
        "active_time": 1686068403,
        "biz_type": 0,
        "category": "sfkzq",
        "create_time": 1686068403,
        "icon": "smart/icon/ay1547018215107OLzeG/3d20ab7b5ab3c13f84b7b4ded95bad46.png",
        "id": "XXX",
        "ip": "",
        "lat": "XXX",
        "local_key": "XXX",
        "lon": "XXX",
        "model": "WT-03W",
        "name": "Back Yard Valve Controller",
        "node_id": "XXX",
        "online": true,
        "owner_id": "XXX",
        "product_id": "1fcnd8xk",
        "product_name": "Valve Controller",
        "status": [
            {
                "code": "switch",
                "value": false
            },
            {
                "code": "battery_percentage",
                "value": 100
            },
            {
                "code": "time_use",
                "value": 190355
            },
            {
                "code": "weather_delay",
                "value": "cancel"
            },
            {
                "code": "countdown",
                "value": 599
            },
            {
                "code": "work_state",
                "value": "idle"
            },
            {
                "code": "smart_weather",
                "value": "sunny"
            },
            {
                "code": "use_time_one",
                "value": 4
            }]
}
```

**Comment by caco3** [comment]
@zaa94 I am trying to get the same device working (https://www.amazon.de/dp/B09P3VRVVB/ref=pe_27091401_487027711_TE_SCE_dp_2)

I tried it with UI config as well as with your config. In both cases I only see disabled entities:

![grafik](https://github.com/leeyuentuen/localtuya/assets/1783586/c9ab7321-194a-45b5-a20f-c8941d1b04b1)

How did you get it working to sync the entities?

**Comment by zaa94** [comment]
Hey @caco3 ! The UI config did not work for me at all. Did you make sure that the device ID for the valve controller in the config file is the `cid`/`node_id` for the valve controller and _not_ the device ID Tuya?

**Comment by caco3** [comment]
Yes, I think so.

This is in `configuration.yaml`:
```yaml
localtuya:  
  - host: 192.168.1.170
    device_id: bf641c545b9e1920da14vi
    local_key: V+IuH~QWR`)v6A{r
    friendly_name: Front Yard Gateway
    protocol_version: "3.4"
    is_gateway: true
  - parent_gateway: bf641c545b9e1920da14vi
    device_id: bf166cmaafamcows
    friendly_name: Front Yard Sprinkler
    protocol_version: "3.4"
    entities:
      - platform: switch
        friendly_name: Front Yard Sprinkler Valve Switch
        id: 1
      - platform: sensor
        friendly_name: Front Yard Sprinkler Valve Battery
        id: 7
        device_class: battery
        unit_of_measurement: "%"
```

And this is the discovery output of `tuya-cli wizard`:
```yaml
  {
    name: 'Wi-Fi hub',
    id: 'bf641c545b9e1920da14vi',
    key: 'V+IuH~QWR`)v6A{r'
  },
  {
    name: 'Bewässerungscomputer',
    id: 'bf166cmaafamcows',
    key: 'U=bYOieeUKH6-O5x'
  }
```
